# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 05:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnpaidUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('last_notification', models.DateTimeField(default=datetime.datetime(2016, 8, 25, 5, 18, 6, 383887, tzinfo=utc))),
            ],
        ),
    ]
