# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-07 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20161106_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unpaidusers',
            name='last_notification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
