# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-08 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_badge'),
        ('payments', '0004_auto_20161107_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(to='main.Badge'),
        ),
    ]
